name: FKStats
version: 1.3.1
author: TheFK
site: http://www.FKProjects.de

main: main.FKStats
api-version: 1.13

commands:
  fkstats:
    description: main-command of this plugin (opens the main-menu) (use "/fkstats h" for help)
    usage: /<command> <args1> <args2>